" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching

" Don't use Ex mode, use Q for formatting
map Q gq

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

set nu
set tabstop=4
set smarttab
set shiftwidth=4 
set autoindent		" always set autoindenting on
set wildmenu
set novisualbell
syntax on
filetype plugin indent on
imap jj <ESC>

" This is for spell check color 
hi clear SpellBad
hi SpellBad term=underline cterm=underline ctermfg=red

" Color scheme
set t_Co=256
let python_highlight_all = 1
colorscheme zenburn
let g:zenburn_high_Contrast=1

" Comment hotkey
map <F6> :s/^/#/g<CR> :/asdasdsad<CR>
map <F7> :s/#//g<CR> :/asdasdsad<CR>

" This is for spell check in tex file
autocmd filetype tex map <F5> :set spell!<CR><Bar>:echo "Spell check: " . strpart("OffOn", 3 * &spell, 3)<CR>

" This is line cursor highlight
autocmd filetype tex map <F6> :set cursorline!<CR><Bar>:echo "Highlight active cursor line: " . strpart("OffOn", 3 * &cursorline, 3)<CR>

" This is comment hotkey for tex file
autocmd filetype tex map <F7> :s/^/% /g<CR> :/asdasdsad<CR>
autocmd filetype tex map <F8> :s/% //g<CR> :/asdasdsad<CR>

" Hotkey to execute python file
autocmd filetype python map <F9> :w<CR>:!python %<CR>
" Hotkey to debug python (using pep8)
autocmd filetype python map <F10> :w<CR>:!pep8 %<CR>
" Set syntax file for python
autocmd filetype python set complete+=k~/.vim/syntax/python.vim isk+=.,(
" Autocompletion of python
autocmd filetype python set omnifunc=pythoncomplete#Complete
let g:SuperTabDefaultCompletionType = "context"
let g:pydiction_location='~/.vim/ftplugin/pydiction/complete-dict'
filetype plugin on
syntax enable

" Autocompletion of html
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags

" pathogen
execute pathogen#infect()

" vim status bar
set laststatus=2
set statusline=%4*%<\ %1*[%F]
set statusline+=%4*\ %5*[%{&encoding}, " encoding
set statusline+=%{&fileformat}%{\"\".((exists(\"+bomb\")\ &&\ &bomb)?\",BOM\":\"\").\"\"}]%m
set statusline+=%4*%=\ %6*%y%4*\ %3*%l%4*,\ %3*%c%4*\ \<\ %2*%P%4*\ \>
highlight User1 ctermfg=red
highlight User2 term=underline cterm=underline ctermfg=green
highlight User3 term=underline cterm=underline ctermfg=yellow
highlight User4 term=underline cterm=underline ctermfg=white
highlight User5 ctermfg=cyan
highlight User6 ctermfg=white
